#Setup Flatpak

- name: Install Flatpak on Debian Systems
  ansible.builtin.package:
    state: latest
    name:
      - flatpak
  when: ansible_os_family == "Debian"

- name: Adding Flathub Repo to Flatpak
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
