#I straight up stole/modified task this from Jay LaCroix at learnlinux.tv
#https://github.com/LearnLinuxTV/personal_ansible_desktop_configs/blob/main/roles/base/tasks/system_setup/microcode.yml

- name: system setup | microcode | install package for amd
  tags: amd,cpu,microcode,system setup
  ansible.builtin.package:
    name: "{{ amd_microcode_package }}"
    state: latest
  when:
    - ansible_processor == "AuthenticAMD"

- name: system setup | microcode | install package for intel
  tags: cpu,intel,microcode,system setup
  ansible.builtin.package:
    name: "{{ intel_microcode_package }}"
    state: latest
  when:
    - ansible_processor == "GenuineIntel"
