#Fedora specific steps for setting up LibreSpeed
- name: Install Dependencies
  ansible.builtin.dnf:
    state: latest
    name:
      - httpd
      - php

- name: Moving Backend Files
  ansible.builtin.copy:
    src: /home/jpatr/.tmp/speedtest/backend
    dest: /var/www/html/
    owner: "apache"
    group: "apache"

- name: Moving HTML File
  ansible.builtin.copy:
    #src: /home/jpatr/.tmp/speedtest/examples/example-singleServer-progressBar.html
    src: /home/jpatr/.tmp/speedtest/index.html
    dest: /var/www/html/index.html
    owner: "apache"
    group: "apache"

- name: Moving speedtest. File
  ansible.builtin.copy:
    src: /home/jpatr/.tmp/speedtest/speedtest.
    dest: /var/www/html/speedtest.
    owner: "apache"
    group: "apache"

- name: Moving speedtest_worker. File
  ansible.builtin.copy:
    src: /home/jpatr/.tmp/speedtest/speedtest_worker.
    dest: /var/www/html/speedtest_worker.
    owner: "apache"
    group: "apache"

- name: Setting up HTTP
  ansible.builtin.copy:
    src: speedHost-fed
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: "0644"

- name: Adding HTTP Firewall Rule
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: Adding HTTPS Firewall Rule
  ansible.posix.firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled

- name: Restarting Apache
  ansible.builtin.service:
    name: httpd
    state: restarted
